# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BerryBear', '0002_remove_program_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='other_info',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
    ]
